// Vue/src/components/DynamicDataGrid/templates/DynamicEditComponent.vue
<script setup lang="ts">
import { computed } from "vue";
import DxTextBox from "devextreme-vue/text-box";
import DxNumberBox from "devextreme-vue/number-box";
import DxDateBox from "devextreme-vue/date-box";
import DxCheckBox from "devextreme-vue/check-box";
import DxSelectBox from "devextreme-vue/select-box";

import type SelectBox from "devextreme/ui/select_box";
import type { ValueChangedEvent as NumberValueChanged } from "devextreme/ui/number_box";
import type { ValueChangedEvent as TextValueChanged } from "devextreme/ui/text_box";
import type { ValueChangedEvent as DateValueChanged } from "devextreme/ui/date_box";
import type { ValueChangedEvent as CheckValueChanged } from "devextreme/ui/check_box";
import type { ValueChangedEvent as SelectValueChanged } from "devextreme/ui/select_box";

import Service from "../../../services/data";
import type { MyCustomType, DynamicType } from "../../../services/data";

const props = defineProps({
  cellInfo: Object,
});

const myDropdownData = computed<MyCustomType[]>(() => {
  return Service.getMyDropdownData();
});
function handleValueChanged(
  e:
    | TextValueChanged
    | NumberValueChanged
    | DateValueChanged
    | CheckValueChanged
    | SelectValueChanged
) {
  if (props.cellInfo?.data.Type == "MyCustomType") {
    const newValue = (e.component as SelectBox).option("selectedItem");
    props.cellInfo?.setValue(newValue);
  } else props.cellInfo?.setValue(e.value);
}
</script>
<template>
  <div v-if="cellInfo?.data.Type == 'String'">
    <DxTextBox
      :value="cellInfo?.data.DynamicValue"
      @value-changed="handleValueChanged"
    />
  </div>
  <div v-else-if="cellInfo?.data.Type == 'Number'">
    <DxNumberBox
      :value="cellInfo?.data.DynamicValue"
      @value-changed="handleValueChanged"
    />
  </div>
  <div v-else-if="cellInfo?.data.Type == 'Date'">
    <DxDateBox
      :value="cellInfo?.data.DynamicValue"
      @value-changed="handleValueChanged"
    />
  </div>
  <div v-else-if="cellInfo?.data.Type == 'Boolean'">
    <DxCheckBox
      :value="cellInfo?.data.DynamicValue"
      @value-changed="handleValueChanged"
    />
  </div>
  <div v-else-if="cellInfo?.data.Type == 'MyCustomType'">
    <DxSelectBox
      :data-source="myDropdownData"
      value-expr="ID"
      display-expr="Name"
      :value="cellInfo.value?.ID"
      @value-changed="handleValueChanged"
    />
  </div>
  <div v-else>
    <span>Unknown type!</span>
  </div>
</template>

// Angular/src/app/dynamic-edit-component/dynamic-edit-component.component.ts
import { Component, Input } from '@angular/core';
import  {
  ColumnEditCellTemplateData,
} from 'devextreme/ui/data_grid';
import { DynamicType, MyCustomType, Service } from '../app.service';
import dxTextBox from 'devextreme/ui/text_box';
import dxNumberBox from 'devextreme/ui/number_box';
import dxDateBox from 'devextreme/ui/date_box';
import dxCheckBox from 'devextreme/ui/check_box';
import dxSelectBox from 'devextreme/ui/select_box';

type EditorComponent =
  | dxTextBox
  | dxNumberBox
  | dxDateBox
  | dxCheckBox
  | dxSelectBox;

@Component({
  selector: 'dynamic-edit-component',
  templateUrl: './dynamic-edit-component.component.html',
  styleUrls: ['./dynamic-edit-component.component.css'],
})
export class DynamicEditComponentComponent {
  @Input() cellInfo: ColumnEditCellTemplateData;

  myDropdownData: MyCustomType[];

  constructor(service: Service) {
    this.myDropdownData = service.getMyDropdownData();
  }

  handleValueChanged(e: { value?: DynamicType; component: EditorComponent }): void {  
    let newValue: DynamicType | MyCustomType['ID'] | unknown = e.value;
    if (this.cellInfo.data.Type == 'MyCustomType') {
      newValue = (e.component as dxSelectBox).option('selectedItem');
    }
    this.cellInfo?.setValue(newValue);
  }
}

<div
  *ngIf="
    cellInfo?.data?.Type == 'String';
    then textBoxTemplate;
    else numberBoxTemplate
  "
></div>

<ng-template #textBoxTemplate>
  <div *ngIf="cellInfo.data?.Type == 'String'; else numberBoxTemplate">
    <dx-text-box
      [value]="cellInfo.data?.DynamicValue"
      (onValueChanged)="handleValueChanged($event)"
    >
    </dx-text-box>
  </div>
</ng-template>

<ng-template #numberBoxTemplate>
  <div *ngIf="cellInfo.data?.Type == 'Number'; else dateBoxTemplate">
    <dx-number-box
      [value]="cellInfo.data?.DynamicValue"
      (onValueChanged)="handleValueChanged($event)"
    >
    </dx-number-box>
  </div>
</ng-template>

<ng-template #dateBoxTemplate>
  <div *ngIf="cellInfo.data?.Type == 'Date'; else checkBoxTemplate">
    <dx-date-box
      [value]="cellInfo.data?.DynamicValue"
      (onValueChanged)="handleValueChanged($event)"
    >
    </dx-date-box>
  </div>
</ng-template>

<ng-template #checkBoxTemplate>
  <div *ngIf="cellInfo.data?.Type == 'Boolean'; else myCustomTemplate">
    <dx-check-box
      [value]="cellInfo.data?.DynamicValue"
      (onValueChanged)="handleValueChanged($event)"
    >
    </dx-check-box>
  </div>
</ng-template>

<ng-template #myCustomTemplate>
  <div *ngIf="cellInfo.data?.Type == 'MyCustomType'; else unknownTemplate">
    <dx-select-box
      [dataSource]="myDropdownData"
      valueExpr="ID"
      displayExpr="Name"
      [value]="cellInfo.value?.ID"
      (onValueChanged)="handleValueChanged($event)"
    >
    </dx-select-box>
  </div>
</ng-template>

<ng-template #unknownTemplate>
  <span>Unknown type!</span>
</ng-template>
